### ISSUE TITLE
SH doesn't support spreading object properties in evalscript

### ISSUE THREAD

**Issue by zcernigoj** [openEOPlatform/openeo-pg-evalscript-converter#78]
Example (also in EOB https://sentinelshare.page.link/xtKS )

```javascript
//VERSION=3
function setup() {
  return {
    input: ["B01","B02","B03", "dataMask"],
    output: { bands: 4 }
  };
}

function evaluatePixel(sample) {
  const bb = {"a": 1, "b": 2};
  const cc = {...bb, "c": 3};

  return [2.5 * sample.B01, 2.5 * sample.B02, 2.5 * sample.B03, sample.dataMask];
}
```

SH returns error

```
Failed to evaluate script!
evalscript.js:11: SyntaxError: Unexpected token ...
  const cc = {...bb, "c": 3};
```

---

`Object.assign(target, source1 [, source2, ...]);` should be used instead

---

in this project:
in `src/pg_to_evalscript/node.py`

`apply_dimension`:
https://github.com/openEOPlatform/openeo-pg-evalscript-converter/blob/ce4f3a1e9382c78b3dc0e6385b2f7a2b84f9ed44/src/pg_to_evalscript/node.py#L285

`merge_cubes`:
https://github.com/openEOPlatform/openeo-pg-evalscript-converter/blob/ce4f3a1e9382c78b3dc0e6385b2f7a2b84f9ed44/src/pg_to_evalscript/node.py#L221

`aggregate_temporal`:
https://github.com/openEOPlatform/openeo-pg-evalscript-converter/blob/ce4f3a1e9382c78b3dc0e6385b2f7a2b84f9ed44/src/pg_to_evalscript/node.py#L379

solution for our project: 

something like
`return apply_dimension(Object.assign({}, arguments, {process}))`

---

found because of https://github.com/openEOPlatform/openeo-pg-evalscript-converter/pull/77#pullrequestreview-991852142

**Comment by Ardweaden** [comment]
Thanks for reminding about this issue, we had noticed it before https://github.com/openEOPlatform/openeo-pg-evalscript-converter/pull/64 but I guess it slipped our minds again.

However, please use https://git.sinergise.com/team-6/openeo-platform/-/issues for issues, closing and republishing there.
